version: '3.8'

# This is the version for release of the docker-compose.yml file that will be used by developers only and not sent to the professor.
# This version can build the images locally, so that the developer can test the application locally.
# This version is needed to build the images with updated code that can be tested locally and pushed to Docker Hub.

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: francescovelluto/se2023-15-thesis-management-backend:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      - REACT_APP_BACKEND_SERVER_PORT=${REACT_APP_BACKEND_SERVER_PORT}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    ports:
      - "${REACT_APP_BACKEND_SERVER_PORT}:${REACT_APP_BACKEND_SERVER_PORT}"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: francescovelluto/se2023-15-thesis-management-frontend:latest
    depends_on:
      - backend
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - REACT_APP_BACKEND_SERVER_PORT=${REACT_APP_BACKEND_SERVER_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - mynetwork

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: francescovelluto/se2023-15-thesis-management-db:latest
    environment:
      - POSTGRES_DB='Thesis-Management-System'
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  mynetwork:
    driver: bridge
